openapi: 3.0.3
info:
  title: My API
  version: 1.0.0
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true

components:
  securitySchemes:
    CognitoAuthorizer: # This is the name of your authorizer
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - "${user_pool_arn}"
paths:
  /function1:
    post:
      security:
        - CognitoAuthorizer: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: integer
              required:
                - field1
                - field2
      x-amazon-apigateway-request-validator: "all"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${functions.function1}/invocations"
        httpMethod: "POST"
        type: "aws_proxy"
        passthroughBehavior: "when_no_match"
        # ... other settings ...
      responses:
        "200":
          description: OK
  /function2:
    post:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${functions.function2}/invocations"
        httpMethod: "POST"
        type: "aws_proxy"
        passthroughBehavior: "when_no_match"
        # ... other settings ...
      responses:
        "200":
          description: OK
